from. import etudiants
from. import professeurs
from. import departement
from. import matiere
from. import classe
from. import personnel
from. import scolarite
from. import note
from. import paiement
